const LOGIN_SUCCESS='LOGIN_SUCCESS';
const LOGIN_FAIL='LOGIN_FAIL';
const LOGIN_REQUEST='LOGIN_REQUEST';
const LOG_OUT='LOG_OUT';
const LOAD_PROFILE='LOAD_PROFILE';


const HOME_VIDEOS="HOME_VIDEOS";
const HOME_VIDEOS_SUCCESS="HOME_VIDEOS_SUCCESS"
const HOME_VIDEOS_FAIL="HOME_VIDEOS_FAIL";
const HOME_VIDEOS_REQUEST="HOME_VIDEOS_REQUEST";




export {HOME_VIDEOS_SUCCESS,HOME_VIDEOS,HOME_VIDEOS_REQUEST,HOME_VIDEOS_FAIL,LOAD_PROFILE,LOG_OUT,LOGIN_SUCCESS,LOGIN_FAIL,LOGIN_REQUEST}